name: Android Build ## name of the workflow

on:
  workflow_dispatch: # To trigger manual build
  release:
    types: [published] # only run the workflow when a new release has been published

env:
  NX_RN_APP_PATH: ${{ 'apps/mobile' }}

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest # using ubuntu latest version / or you can use a specific version

    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Build Android Composite
        uses: ./.github/actions/android-release-build@v1
        with:
          app-path: ${{ env.NX_RN_APP_PATH }}
          signing-key: ${{ secrets.ANDROID_SIGNING_KEY }}
          keystore-alias: ${{ secrets.ANDROID_ALIAS }}
          keystore-password: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          key-password: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: ${{ env.NX_RN_APP_PATH }}/android/app/build/outputs/apk/release

  deploy:
    needs: [android-build]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: app-release.apk

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: davi.santos/Codemagic-POC
          token: ${{secrets.APPCENTER_TOKEN_ANDROID}}
          group: Public
          file: app-release.apk
          notifyTesters: true
          debug: false

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: app-release.apk
